pushing the code files
Redback-Operations/redback-orion-web pull request #7
Opened 2024-05-09 14:43 UTC by Mihirotron

2024-05-10 16:04 UTC, doubleedesign requested changes

2024-05-10 16:04 UTC, doubleedesign commented on src/CrowdDataDashboard.html
> +    <header>
Everything in the `body` needs to be broken up into React components.

2024-05-10 16:04 UTC, doubleedesign commented on src/ResourcesAndSupport.html
> +        <section class="guidelines">
Likewise for this file - React components. There should not be any `.html` files added.

2024-05-10 16:04 UTC, doubleedesign commented on src/assets/styles.css
> +{
CSS should be scoped to each component and placed in the `styled.ts` file in each component folder. Please use [the generator](https://redback-operations.github.io/redback-documentation/docs/web-mobile-app-dev/frontend/new-components) to create the proper files to start with.

2024-05-10 16:04 UTC, doubleedesign commented on src/routes/Root/React.jsx
> +<div className="Group2" style={{width: 1919, height: 2663, position: 'relative'}}>
What is this file for?

2024-05-10 16:04 UTC, doubleedesign commented on src/routes/Root/scripts.js
> +document.addEventListener("DOMContentLoaded", function() {
Please refactor all of this to belong in the relevant React components, using React conventions.

2024-05-14 07:50 UTC, doubleedesign commented
I can see a lot of the build errors are related to whitespace, which is easy to fix by setting up your IDE to auto-format on save using the project's ESLint configuration. See [this doc](https://redback-operations.github.io/redback-documentation/docs/web-mobile-app-dev/frontend/submitting-work) for more information 🙂

2024-07-01 12:47 UTC, ben-AI-cybersec commented
No attempt made to integrate reviewers requests. Code doesn't run, closing PR

2024-07-01 12:47 UTC, closed without merging